config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :quote, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/extra.rb
class Extra < ApplicationRecord
  belongs_to :service
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :service
  validates_presence_of :name , :price
end

app/models/service.rb
class Service < ApplicationRecord
    has_many :extras, dependent: :destroy
    has_many :urgencies, dependent: :destroy
    has_many :levels, dependent: :destroy
    accepts_nested_attributes_for :extras, :urgencies, :levels, allow_destroy: true

    validates_presence_of :name, :price, :extras, :urgencies,:levels

end

app/models/urgency.rb
class Urgency < ApplicationRecord
  belongs_to :service
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/quote_controller.rb
class QuoteController < ApplicationController
  before_action :find_service

  def index
    @services = Service.all
    @urgencies = Urgency.all
  end

def find_service
  @service = Service.find_by(id: params[:service_id].presence)
  @urgency = Urgency.find_by(id: params[:urgency_id].presence)
end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]

  # GET /services or /services.json
  def index
    @services = Service.all
  end

  # GET /services/1 or /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to service_url(@service), notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to service_url(@service), notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:name, :price, extras_attributes: [:name, :description, :price,:_destroy], 
                                       urgencies_attributes: [:duration, :price,:_destroy], 
                                       levels_attributes: [:name, :price,:_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quote_helper.rb
module QuoteHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/home/index.html.erb
 <section class="relative lg:h-screen">
    <!-- Start of header -->


    <div class="lg:flex justify-center items-center h-full pb-16 lg:pb-0">
      <img class="pt-24 w-full lg:pt-0 lg:w-auto" src= "<%= image_url "coffee_hero.png" %>" alt="hero">
      <div class="mx-4 mt-8 lg:mt-0 lg:ml-16">
        <span class="block uppercase text-sm lg:text-base lg:font-semibold mb-2 lg:mb-4 text-gray-700">I help 
          businesses to</span>
        <h1 class="text-5xl lg:text-7xl uppercase text-gray-900 font-medium mb-4 lg:mb-8"> Build and Ship <span
            class="block font-black">Projects
            fast</span>
          </h1>
        <a class="inline-block uppercase text-sm text-center font-bold px-5 py-3 lg:px-10 lg:py-4 rounded-tr-3xl rounded-bl-3xl bg-gray-900 text-yellow-50 hover:bg-gray-700 focus:ring-2 focus:ring-yellow-300"
          href="/quote"> See how much it costs to hire me</a>
      </div>
    </div>
  </section>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body >
      
    <%= yield %>
  </body>
</html>

app/views/quote/_order.html.erb
        <div class="mt-10 lg:mt-0">
          <h2 class="text-lg font-medium text-gray-900">Order summary</h2>

          <div class="mt-4 rounded-lg border border-gray-200 bg-white shadow-sm">
            <h3 class="sr-only">Items ordered</h3>
            <ul role="list" class="divide-y divide-gray-200">
              <li class="flex px-4 py-6 sm:px-6">
                <div class="ml-6 flex flex-1 flex-col">
                 <h2 class="text-lg font-medium text-gray-900">Service</h2>

                  <div class="flex">
                    <div class="min-w-0 flex-1">
                      <h4 class="text-sm">
                        <a href="#" class="font-medium text-gray-700 hover:text-gray-800"><%= @service&.name %></a>
                      </h4>
                    </div>
                  </div>

                  <div class="flex flex-1 items-end justify-between pt-2">
                    <p class="mt-1 text-sm font-medium text-gray-900"><%= number_to_currency @service&.price %></p>

                 
                  </div>
                </div>
              </li>
              <li class="flex px-4 py-6 sm:px-6">
                <div class="ml-6 flex flex-1 flex-col">
                 <h2 class="text-lg font-medium text-gray-900">Urgency</h2>

                  <div class="flex justify-end">
                    <div class="min-w-0 flex-1">
                      <h4 class="text-sm">
                        <a href="#" class="font-medium text-gray-700 hover:text-gray-800"><%= @urgency&.duration %> days</a>
                      </h4>
                    </div>
                  </div>

                    <div class="flex flex-1  pt-2">
                      <p class="mt-1 text-sm font-medium text-gray-900"><%= number_to_currency @urgency&.price %></p>
                    </div>
                </div>
              </li>

              <!-- More products... -->
            </ul>
            <dl class="space-y-6 border-t border-gray-200 px-4 py-6 sm:px-6">
              <div class="flex items-center justify-between">
                <dt class="text-sm">Subtotal</dt>
                <dd class="text-sm font-medium text-gray-900">$64.00</dd>
              </div>
              <div class="flex items-center justify-between">
                <dt class="text-sm">Shipping</dt>
                <dd class="text-sm font-medium text-gray-900">$5.00</dd>
              </div>
              <div class="flex items-center justify-between">
                <dt class="text-sm">Taxes</dt>
                <dd class="text-sm font-medium text-gray-900">$5.52</dd>
              </div>
              <div class="flex items-center justify-between border-t border-gray-200 pt-6">
                <dt class="text-base font-medium">Total</dt>
                <dd class="text-base font-medium text-gray-900"><%= @service&.price %></dd>
              </div>
            </dl>

            <div class="border-t border-gray-200 px-4 py-6 sm:px-6">
              <button type="submit" class="w-full rounded-md border border-transparent bg-indigo-600 px-4 py-3 text-base font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-50">Confirm order</button>
            </div>
          </div>
        </div>

app/views/quote/index.html.erb
   <%= turbo_frame_tag "quote"  do%> 

<div class="bg-gray-50 ">
 

  <main class="mx-auto max-w-7xl px-4 pb-24 pt-16 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-2xl lg:max-w-none">
      <h1 class="sr-only">Get Quote</h1>
      <%= form_with model: @service, url: quote_index_path, method: :get, class: "lg:grid lg:grid-cols-2 lg:gap-x-12 xl:gap-x-16"   do |form| %>
        <div>
          <div>
            <h2 class="text-lg font-medium text-gray-900">Lets work Together</h2>

            <div>
                <label for="country" class="block text-sm font-medium text-gray-700">Select Service</label>
                <div class="mt-4">
                 <%= select_tag :service_id, options_from_collection_for_select(@services, "id", "name", @service&.id), prompt: "- Please select -", class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", onchange: "this.form.requestSubmit()" %>
                </div>
            </div>
            <div>
                <label for="country" class="block text-sm font-medium text-gray-700">Select Urgency</label>
                <div class="mt-4">
                 <%= select_tag :urgency_id, options_from_collection_for_select(@urgencies, "id", "duration", @urgency&.id), prompt: "- Please select -", class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", onchange: "this.form.requestSubmit()" %>
                </div>
            </div>


          </div>

          <div class="mt-10 border-t border-gray-200 pt-10">
            <h2 class="text-lg font-medium text-gray-900">Shipping information</h2>

            <div class="mt-4 grid grid-cols-1 gap-y-6 sm:grid-cols-2 sm:gap-x-4">
              <div>
                <label for="first-name" class="block text-sm font-medium text-gray-700">First name</label>
                <div class="mt-1">
                  <input type="text" id="first-name" name="first-name" autocomplete="given-name" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
                </div>
              </div>

              <div>
                <label for="last-name" class="block text-sm font-medium text-gray-700">Last name</label>
                <div class="mt-1">
                  <input type="text" id="last-name" name="last-name" autocomplete="family-name" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
                </div>
              </div>

              <div class="sm:col-span-2">
                <label for="company" class="block text-sm font-medium text-gray-700">Company</label>
                <div class="mt-1">
                  <input type="text" name="company" id="company" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
                </div>
              </div>

              <div class="sm:col-span-2">
                <label for="address" class="block text-sm font-medium text-gray-700">Address</label>
                <div class="mt-1">
                  <input type="text" name="address" id="address" autocomplete="street-address" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
                </div>
              </div>

              <div class="sm:col-span-2">
                <label for="apartment" class="block text-sm font-medium text-gray-700">Apartment, suite, etc.</label>
                <div class="mt-1">
                  <input type="text" name="apartment" id="apartment" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
                </div>
              </div>

              <div>
                <label for="city" class="block text-sm font-medium text-gray-700">City</label>
                <div class="mt-1">
                  <input type="text" name="city" id="city" autocomplete="address-level2" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
                </div>
              </div>

              <div>
                <label for="country" class="block text-sm font-medium text-gray-700">Country</label>
                <div class="mt-1">
                  <select id="country" name="country" autocomplete="country-name" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
                    <option>United States</option>
                    <option>Canada</option>
                    <option>Mexico</option>
                  </select>
                </div>
              </div>

              <div>
                <label for="region" class="block text-sm font-medium text-gray-700">State / Province</label>
                <div class="mt-1">
                  <input type="text" name="region" id="region" autocomplete="address-level1" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
                </div>
              </div>

              <div>
                <label for="postal-code" class="block text-sm font-medium text-gray-700">Postal code</label>
                <div class="mt-1">
                  <input type="text" name="postal-code" id="postal-code" autocomplete="postal-code" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
                </div>
              </div>

              <div class="sm:col-span-2">
                <label for="phone" class="block text-sm font-medium text-gray-700">Phone</label>
                <div class="mt-1">
                  <input type="text" name="phone" id="phone" autocomplete="tel" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
                </div>
              </div>
            </div>
          </div>

          <div class="mt-10 border-t border-gray-200 pt-10">
            <fieldset>
              <legend class="text-lg font-medium text-gray-900">Delivery method</legend>

              <div class="mt-4 grid grid-cols-1 gap-y-6 sm:grid-cols-2 sm:gap-x-4">
                <!--
                  Checked: "border-transparent", Not Checked: "border-gray-300"
                  Active: "ring-2 ring-indigo-500"
                -->
                <label class="relative flex cursor-pointer rounded-lg border bg-white p-4 shadow-sm focus:outline-none">
                  <input type="radio" name="delivery-method" value="Standard" class="sr-only" aria-labelledby="delivery-method-0-label" aria-describedby="delivery-method-0-description-0 delivery-method-0-description-1">
                  <span class="flex flex-1">
                    <span class="flex flex-col">
                      <span id="delivery-method-0-label" class="block text-sm font-medium text-gray-900">Standard</span>
                      <span id="delivery-method-0-description-0" class="mt-1 flex items-center text-sm text-gray-500">4–10 business days</span>
                      <span id="delivery-method-0-description-1" class="mt-6 text-sm font-medium text-gray-900">$5.00</span>
                    </span>
                  </span>
                  <!-- Not Checked: "hidden" -->
                  <svg class="h-5 w-5 text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
                  </svg>
                  <!--
                    Active: "border", Not Active: "border-2"
                    Checked: "border-indigo-500", Not Checked: "border-transparent"
                  -->
                  <span class="pointer-events-none absolute -inset-px rounded-lg border-2" aria-hidden="true"></span>
                </label>
                <!--
                  Checked: "border-transparent", Not Checked: "border-gray-300"
                  Active: "ring-2 ring-indigo-500"
                -->
                <label class="relative flex cursor-pointer rounded-lg border bg-white p-4 shadow-sm focus:outline-none">
                  <input type="radio" name="delivery-method" value="Express" class="sr-only" aria-labelledby="delivery-method-1-label" aria-describedby="delivery-method-1-description-0 delivery-method-1-description-1">
                  <span class="flex flex-1">
                    <span class="flex flex-col">
                      <span id="delivery-method-1-label" class="block text-sm font-medium text-gray-900">Express</span>
                      <span id="delivery-method-1-description-0" class="mt-1 flex items-center text-sm text-gray-500">2–5 business days</span>
                      <span id="delivery-method-1-description-1" class="mt-6 text-sm font-medium text-gray-900">$16.00</span>
                    </span>
                  </span>
                  <!-- Not Checked: "hidden" -->
                  <svg class="h-5 w-5 text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
                  </svg>
                  <!--
                    Active: "border", Not Active: "border-2"
                    Checked: "border-indigo-500", Not Checked: "border-transparent"
                  -->
                  <span class="pointer-events-none absolute -inset-px rounded-lg border-2" aria-hidden="true"></span>
                </label>
              </div>
            </fieldset>
          </div>

          <!-- Payment -->
          <div class="mt-10 border-t border-gray-200 pt-10">
            <h2 class="text-lg font-medium text-gray-900">Payment</h2>

            <fieldset class="mt-4">
              <legend class="sr-only">Payment type</legend>
              <div class="space-y-4 sm:flex sm:items-center sm:space-x-10 sm:space-y-0">
                <div class="flex items-center">
                  <input id="credit-card" name="payment-type" type="radio" checked class="h-4 w-4 border-gray-300 text-indigo-600 focus:ring-indigo-500">
                  <label for="credit-card" class="ml-3 block text-sm font-medium text-gray-700">Credit card</label>
                </div>
                <div class="flex items-center">
                  <input id="paypal" name="payment-type" type="radio" class="h-4 w-4 border-gray-300 text-indigo-600 focus:ring-indigo-500">
                  <label for="paypal" class="ml-3 block text-sm font-medium text-gray-700">PayPal</label>
                </div>
                <div class="flex items-center">
                  <input id="etransfer" name="payment-type" type="radio" class="h-4 w-4 border-gray-300 text-indigo-600 focus:ring-indigo-500">
                  <label for="etransfer" class="ml-3 block text-sm font-medium text-gray-700">eTransfer</label>
                </div>
              </div>
            </fieldset>

            <div class="mt-6 grid grid-cols-4 gap-x-4 gap-y-6">
              <div class="col-span-4">
                <label for="card-number" class="block text-sm font-medium text-gray-700">Card number</label>
                <div class="mt-1">
                  <input type="text" id="card-number" name="card-number" autocomplete="cc-number" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
                </div>
              </div>

              <div class="col-span-4">
                <label for="name-on-card" class="block text-sm font-medium text-gray-700">Name on card</label>
                <div class="mt-1">
                  <input type="text" id="name-on-card" name="name-on-card" autocomplete="cc-name" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
                </div>
              </div>

              <div class="col-span-3">
                <label for="expiration-date" class="block text-sm font-medium text-gray-700">Expiration date (MM/YY)</label>
                <div class="mt-1">
                  <input type="text" name="expiration-date" id="expiration-date" autocomplete="cc-exp" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
                </div>
              </div>

              <div>
                <label for="cvc" class="block text-sm font-medium text-gray-700">CVC</label>
                <div class="mt-1">
                  <input type="text" name="cvc" id="cvc" autocomplete="csc" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Order summary -->
       <%= render "order" %>
     <% end %>
 
    </div>
  </main>
</div>
   <% end %> 

app/views/services/_extra_form.html.erb
<div>
           <div class="col-span-full">
            <%= form.label :name, class:"block text-sm font-medium text-gray-700" %>
            <%= form.text_field :name, class:"block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
            </div>
            <div class="col-span-full">
            <%= form.label :description, class:"block text-sm font-medium text-gray-700" %>
            <%= form.text_field :description, class:"block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
            </div>

            <div class="col-span-full">
            <%=form.label :price, class:"block text-sm font-medium text-gray-700" %>
            <%= form.text_field :price, class:"block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
            
            </div>
            

</div>

app/views/services/_form.html.erb
        <%= form_with model: service, class: "mt-6" do |form| %>
          <div class="grid">
          
          
          <% if service.errors.any? %>
            <div style="color: red">
              <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

              <ul>
                <% service.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div  class="col-span-full">
            <%= form.label :name, class:"block text-sm font-medium text-gray-700" %>
            <%= form.text_field :name, class:"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
          </div>

          <div class="col-span-full">
            <%= form.label :price, class:"block text-sm font-medium text-gray-700" %>
            <%= form.text_field :price, class:"block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
          </div>
          <div class= "text-blue-600 cursor-pointer">
           <%= link_to_add_nested(form, :levels, '#levels', partial: 'level_form') %>
          
          </div>
          <div id = "levels">
            <%= form.fields_for  :levels do |level_form| %>
             <%= render "level_form", form: level_form  %>
            <% end %>
          </div>

          <div>
          <h2 class="text-green-950">Fields for  extras</h2>
            <%= form.fields_for  :extra do |extra_form| %>
            <%= render "extra_form", form: extra_form  %>
            <% end %>
          </div>

          <div>
          <h2 class="text-green-950">Fields for  urgencies</h2>
            <%= form.fields_for  :urgency do |urgency_form| %>
             <%= render "urgency_form", form: urgency_form  %>

            <% end %>
          </div>

          <div>
            <%= form.submit class:"mt-6 w-full rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"%>
          </div>
        </div>
        <% end %>

app/views/services/_level_form.html.erb
<div class= "level_form">
           <h2 class="text-green-950">Fields for  level</h2>

           <div  class="col-span-full">
              <%= form.label :name, class:"block text-sm font-medium text-gray-700" %>
            <%= form.text_field :name, class:"block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"%>
            </div>

            <div  class="col-span-full">
            <%=form.label :price, class:"block text-sm font-medium text-gray-700" %>
            <%= form.text_field :price, class:"block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
            </div>

         <%= link_to_remove_nested(form) %>

</div>

app/views/services/_service.html.erb
<div id="<%= dom_id service %>">
  <p>
    <strong>Name:</strong>
    <%= service.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= service.price %>
  </p>

</div>

app/views/services/_urgency_form.html.erb
<div>
          <div  class="col-span-full">
            <%= form.label :duration, class:"block text-sm font-medium text-gray-700" %>
            <%= form.number_field :duration, class:"block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
            </div>
            <div  class="col-span-full">
            <%= form.label :price, class:"block text-sm font-medium text-gray-700" %>
            <%= form.text_field :price, class:"block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
            </div>



</div>

app/views/services/edit.html.erb
<%= render  "shared/container" do %>

<h1 class= "text-lg font-medium text-gray-900">Editing service</h1>

<%= render "form", service: @service %>

<br>

<div>
  <%= link_to "Show this service", @service %> |
  <%= link_to "Back to services", services_path %>
</div>
<% end %>

app/views/services/index.html.erb
<%= render  "shared/container" do %>

<p style="color: green"><%= notice %></p>

<h1 class= "text-lg font-medium text-gray-900">Services</h1>

<div id="services">
  <% @services.each do |service| %>
    <%= render service %>
    <p>
      <%= link_to "Show this service", service, class:"text-lg font-medium text-gray-900" %>
    </p>
  <% end %>
</div>

<%= link_to "New service", new_service_path,class: "text-lg font-medium text-gray-900" %>
<% end %>

app/views/services/new.html.erb
<%= render  "shared/container" do %>
<div>
<h1 class= "text-lg font-medium text-gray-900">New service</h1>

<%= render "form", service: @service %>

<br>

<div>
  <%= link_to "Back to services", services_path , class: "text-lg font-medium text-gray-900"%>
</div>



</div>

<% end %>

app/views/services/show.html.erb
<%= render  "shared/container" do %>
<p style="color: green"><%= notice %></p>

<%= render @service %>

<div>
  <%= link_to "Edit this service", edit_service_path(@service),class: "text-lg font-medium text-gray-900" %> |
  <%= link_to "Back to services", services_path %>

  <%= button_to "Destroy this service", @service, method: :delete, class: "text-lg font-medium text-gray-900" %>
</div>
<% end %>

app/views/shared/_container.html.erb
<main class="lg:flex lg:min-h-full lg:flex-row-reverse lg:overflow-hidden">

  <section  class="flex-auto overflow-y-auto px-4 pb-16 pt-12 sm:px-6 sm:pt-16 lg:px-8 lg:pb-24 lg:pt-0">
      <div class="mx-auto max-w-lg lg:pt-16">
            <%= yield %>
       <div></div>
  </section>
</main>